on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: cldreg.azurecr.io
        username: ${{ secrets.acr_cldreg_username }}
        password: ${{ secrets.acr_cldreg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/app" -f  "app/Dockerfile" -t cldreg.azurecr.io/k8scld:${{ github.sha }} --label dockerfile-path=app/Dockerfile
        docker push cldreg.azurecr.io/k8scld:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_k8scld_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep k8s-test | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace k8s-test`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: k8s-test
        container-registry-url: cldreg.azurecr.io
        container-registry-username: ${{ secrets.acr_cldreg_username }}
        container-registry-password: ${{ secrets.acr_cldreg_password }}
        secret-name: k8sclddockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: k8s-test
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          cldreg.azurecr.io/k8scld:${{ github.sha }}
        imagepullsecrets: |
          k8sclddockerauth
